### PR TITLE
Fix logo href

### LINKED ISSUE #35: Remove a glove from the Cow protocol logo in Footer on a mouse hover
When hover a mouse on the Cow protocol logo in the Footer, a glove appears like a hovered effect. 
However, nothing happens when click on the logo. 
image

So it would be nice to remove a glove effect from the Cow protocol logo in Footer on a mouse hover
OR
make it clickable and navigate a user to the top of the page

### PR DESCRIPTION
**Pull request by fairlighteth**
Fixes https://github.com/gnosis/cow-web/issues/35

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @biocom , just to clarify: now the logo navigates to the Cow.fi for all environments. 
I mean, even if I press on the logo from https://develop.cow.fi/ , I will be redirected to https://cow.fi/ with no respect of environment I'm currently working on. 
Is that correct?

**Comment by fairlighteth** [comment]
@elena-zh I hadn't considered that case. That's not right indeed. Will revert to use '/'.

**Comment by fairlighteth** [comment]
Should be fixed now @elena-zh

**Review by anxolin — COMMENTED** [review]
weird, if i click, it redirects me not to the root of the current domain, but to cow.fi

**Review by elena-zh — APPROVED** [review]
Now I'm navigated to the top of the page. 
Thanks!

**Comment by fairlighteth** [comment]
@anxolin Should be fixed now, as I removed the absolute url, and added back the '/' .

**Pull request merged**
